# Generated by Django 4.2.20 on 2025-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0018_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
